- name: Suppression DHCP
  hosts: csr1000
  gather_facts: false

  tasks:
    - name: Supprime le pool DHCP
      cisco.ios.ios_command:
        commands:
        - conf t
        - no ip dhcp pool pooltest2
