- name: Config NAT/PAT CSR1000
  hosts: csr1000
  gather_facts: false

  tasks:
    - name: config acl
      cisco.ios.ios_config:
        lines: access-list 2 permit 192.168.{{ item }}.0 0.0.0.255
      loop:
        - 2
        - 3
        - 4

    - name: config nat
      cisco.ios.ios_config:
        lines:
        - ip nat inside source list 2 interface g1 overload

    - name: config ip nat inside
      cisco.ios.ios_config:
        lines: ip nat inside
        parents: int {{ item }}
      loop:
        - g2
        - g3
        - g4

    - name: config ip nat outside
      cisco.ios.ios_config:
        lines: ip nat outside
        parents: int g1

    - name: config PAT statique
      cisco.ios.ios_config:
        lines: ip nat inside source static tcp 192.168.{{ item.addr }}.2 {{ item.portlan }} int g1 {{ item.portwan }}
      loop:
        - addr: 3
          portlan: 80
          portwan: 80
        - addr: 4
          portlan: 22
          portwan: 2222
